### ISSUE TITLE
Issue viewing from Android

### ISSUE THREAD

**Issue by kirbyfan64** [AvetisG/TubeToTune#6]
On Chrome on my Nexus 5, the box where you enter a URL is covered by the box asking to star this on GitHub. That kinda kills the app's purpose... :)

**Comment by AvetisG** [comment]
@kirbyfan64 yeap the mobile is definitely a little wonky. Will look into this and check in the new fix :) Thank you for your contribution!

**Comment by AvetisG** [comment]
@kirbyfan64 you can now try it on any of your mobile devices - a change has been pushed to take care of all the problems. Once again thank you for your contribution!

**Comment by kirbyfan64** [comment]
Looks great! Thanks!
