### ISSUE TITLE
Don't bundle a zip if only one file is being downloaded

### ISSUE THREAD

**Issue by kirbyfan64** [AvetisG/TubeToTune#7]
On Android, unzipping stuff tends to be a pain in the neck...

On the other hand, could there be an option for individual download links instead of a zip? Same reasons. ;)

**Comment by AvetisG** [comment]
Yeap this is a great point I was going to include this feature sooner than later but this is a great nudge to push me to write it up!

Thank you for the motivation :)

**Comment by AvetisG** [comment]
@kirbyfan64 nvm just pushed the changes now haha it should be all set now and when you are trying to convert/download one file it will not be zipped anymore.

**Comment by kirbyfan64** [comment]
@AvetisG Thanks again!
