### ISSUE TITLE
An error has occurred?

### ISSUE THREAD

**Issue by kirbyfan64** [AvetisG/TubeToTune#8]
Dang, I'm starting to feel like the issue creator. ;)

See, it seems that I'm constantly getting "An error occurred" messages. One of the sample URLs that I tried is https://youtu.be/UK2H2j0Ufy8. It would convert successfully, but tapping Download took me to a page saying an error occurred. 5 times.

**Comment by AvetisG** [comment]
haha that's great. That's the reason open source is awesome :) Thank you for your efforts by the way!

It seems like the link format is not being handled correctly which is a bit of an interesting issue. For the time being use the un-shortened version of the link and once I figure this one out you can revert to using the shortened format once again!

**Comment by kirbyfan64** [comment]
Ok! Thanks! Again!

**Comment by kirbyfan64** [comment]
I think this might have something to do with file size? Trying to download a 10-minute file, I gave up. One around a minute long only gave me 1 error occurred message.

**Comment by AvetisG** [comment]
@kirbyfan64 hmm that's interesting. The error thing is something on the list as in for giving a more specific error but as for not being able to download a 10 minute video that shouldn't be a problem I have downloaded an 1 hour long video! Will definitely look into this also if you don't mind could you post the video link here just so that I have a specific test case. If not that is okay too. Thank you for your feedback it's very helpful!

**Comment by kirbyfan64** [comment]
https://youtu.be/RD1hHX59sPg

(yeah, I'm a VGM fan...)

I believe I had also tried it with the full link and still got the empty error page with the unrendered XML/HTML.

**Comment by AvetisG** [comment]
Awesome! :)

Yes, that makes sense. My long term goal is to let people type the name of the video and auto generate the video link so that there are no user-errors while manually entering since some links are compressed and some are not.

Hold on tight and when it is all solved I will shoot a comment back! :)

**Comment by kirbyfan64** [comment]
I think this is fixed? Hasn't happened to me in several days. Weird. I'm guessing it was something external (e.g. a YouTube or .NET bug). Whatever. Issue solved! :)

**Comment by AvetisG** [comment]
@kirbyfan64 Interesting... nope a fix hasn't been pushed out yet which makes me thing this was a network related issue. I guess another issue that I should create is or and more specific error messaging!

**Comment by kirbyfan64** [comment]
Ack! I spoke too soon. It worked *perfectly* yesterday, but it came back today.

Here's a screenshot of the error [on Dropbox](https://www.dropbox.com/s/zt4ndwvwy9mdpgq/Screenshot_2015-07-12-13-24-01.png?dl=0).

**Comment by kirbyfan64** [comment]
Now there message changed. Screenshot at https://www.dropbox.com/s/k22oco2idu561yl/Screenshot_2015-07-12-13-36-16.png?dl=0.

**Comment by kirbyfan64** [comment]
Message is:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Message>
No HTTP resource was found that matches the request URI 'http://tubetotune.apphb.com:16744/api/download/'.
</Message>
</Error>
```

**Comment by kirbyfan64** [comment]
Failing URL: https://youtu.be/bn0glv4652Q.

**Comment by kirbyfan64** [comment]
I think I'm getting somewhere! Both of these errors are quite possibly due to YoutubeExtractor, not your app.

The second message is due to the titles. Notice the error URL has a pound in it. The solution seems to be to change line 12 of `FileNameGenerationHelper.cs` to:

```csharp
string regexSearch = new string(Path.GetInvalidFileNameChars()) + new string(Path.GetInvalidPathChars()) + "#";
```

**Comment by kirbyfan64** [comment]
@AvetisG I want to try to fix the former issue, but, being on Linux, I have *no* clue how to run this. I tried running `xbuild`, and it created a bunch of DLLs. Which is great and all...

...but what do I do now? `xsp` doesn't do anything useful.

**Comment by AvetisG** [comment]
This I think is also resolved and the new updates are going to let you see the full error message instead of just getting an error occurred :)
